linters:
  # Default linters enabled
  # See: https://golangci-lint.run/usage/linters/#enabled-by-default-linters

  # Additional linters enabled
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    # - contextcheck #< TODO Re-enable when https://github.com/golangci/golangci-lint/issues/2649 is resolved
    - cyclop
    - decorder
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - gochecknoglobals
    - goconst
    - gocritic
    - godot
    - gofmt
    - gomoddirectives
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nosprintfhostport
    - prealloc
    - predeclared
    - revive
    - tenv
    - testpackage
    - unconvert
    - unparam
    # - wastedassign #< TODO Re-enable when https://github.com/golangci/golangci-lint/issues/2649 is resolved
    - whitespace
    - wrapcheck
